### ISSUE TITLE
Problem with script

### ISSUE THREAD

**Issue by HououinKyouma01** [nian0114/port_miui_oneplus2#1]
> sed: can't read ramdisk/default.prop: No such file or directory
> sed: can't read ramdisk/fstab.qcom: No such file or directory

These lines

```
sed -i "/\s*ro.secureboot.devicelock.*$/d" ramdisk/default.prop
sed -i "/\s*system.*$/d" ramdisk/fstab.qcom
```

I don't really know what are you doing here (I must finally learn how regex works). sed is for text operations, but I don't understand what, for example is this :
`"/\s*ro.secureboot.devicelock.*$/d"`
And those files are important, so even if rest would be ok...

Ah, one more thing 
`sudo chown -R nian:nian output`
This wouldn't work for anyone than you :) So maybe it's better to set variable based on whami?

Btw mashmallow build will be possible, when xiaomi release 6.0 based miui for Note Pro?

**Edit:**
I add 2 lines which creates those files before _sed_, no errors after this.

**Edit2**

> Start Modify APPS  ...
> ../../tools/1.patch:282: trailing whitespace.
> 
> Checking patch miuisystem/smali/miui/drm/DrmManager.smali...
> error: miuisystem/smali/miui/drm/DrmManager.smali: No such file or directory
> Checking patch ThemeManager/smali/miui/resourcebrowser/view/ResourceOperationHandler.smali...
> error: ThemeManager/smali/miui/resourcebrowser/view/ResourceOperationHandler.smali: No such file or directory
> Checking patch miuisystem/smali/miui/drm/DrmManager.smali...
> error: miuisystem/smali/miui/drm/DrmManager.smali: No such file or directory
> 
> +++++++++++
> - Summary +
>   +++++++++++
> - Apply patch successfully!
>   Checking patch services.jar.out/smali/com/miui/server/SecurityManagerService.smali...
>   Checking patch services.jar.out/smali/com/android/server/pm/PackageManagerService.smali...
>   Applied patch services.jar.out/smali/com/miui/server/SecurityManagerService.smali cleanly.
>   Applied patch services.jar.out/smali/com/android/server/pm/PackageManagerService.smali cleanly.
> 
> +++++++++++
> - Summary +
>   +++++++++++
> - Apply patch successfully!
>   Checking patch android.policy.jar.out/smali/com/android/internal/policy/impl/MiuiGlobalActions$1.smali...
>   Checking patch android.policy.jar.out/smali/com/android/internal/policy/impl/MiuiGlobalActions.smali...
>   Applied patch android.policy.jar.out/smali/com/android/internal/policy/impl/MiuiGlobalActions$1.smali cleanly.
>   Applied patch android.policy.jar.out/smali/com/android/internal/policy/impl/MiuiGlobalActions.smali cleanly.
> 
> +++++++++++
> - Summary +
>   +++++++++++
> - Apply patch successfully!
>   mv: cannot stat ‘services.jar.out/dist/services.jar’: No such file or directory
>   mv: cannot stat ‘android.policy.jar.out/dist/android.policy.jar’: No such file or directory
>   cp: cannot stat ‘../ThemeManager/build/apk/classes.dex’: No such file or directory
>   cp: cannot stat ‘../miuisystem/build/apk/classes.dex’: No such file or directory
>   Start Modify System ...
>   Bye AD ...
>   Add StockSettings ...
>   Disable Recovery Auto Install ...
>   Start Oneplus Port
>   Tweak build.prop
>   Add Xposed ...
>   Build system.new.dat ...
>   Final Step ...
>   mv: cannot stat ‘workspace/boot.img’: No such file or directory
>   cp: cannot stat ‘tools/root’: No such file or directory

**Comment by nian0114** [comment]
sudo chown -R nian:nian output  you must change "nian" as your own username.

**Comment by nian0114** [comment]
sed -i "/\s_ro.secureboot.devicelock._$/d" ramdisk/default.prop
sed -i "/\s_system._$/d" ramdisk/fstab.qcom

MIUI have assest in boot.img,so you need to remove it

**Comment by nian0114** [comment]
Start Modify APPS ... error must sure your Ubuntu can mkdir.
